// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1rqEeudiqGhhegclR8JIxhZGNpkjTno',
    appId: '1:857794246784:web:7f46b9903844c2a2d28e65',
    messagingSenderId: '857794246784',
    projectId: 'sorcevapla-e595f',
    authDomain: 'sorcevapla-e595f.firebaseapp.com',
    storageBucket: 'sorcevapla-e595f.appspot.com',
    measurementId: 'G-GSNNV9LSSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8N42WW8ngYWpCrxHRoW0Y60xJAbTYLA',
    appId: '1:857794246784:android:b85c4d8823b65fbed28e65',
    messagingSenderId: '857794246784',
    projectId: 'sorcevapla-e595f',
    storageBucket: 'sorcevapla-e595f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz8H-Ov842BlyJluJ2e4JBSx3Hstdtt4U',
    appId: '1:857794246784:ios:c848df9564b39f82d28e65',
    messagingSenderId: '857794246784',
    projectId: 'sorcevapla-e595f',
    storageBucket: 'sorcevapla-e595f.appspot.com',
    iosClientId: '857794246784-6325e4c5uvghe41ta748je2ul9foosvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sorcevapla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz8H-Ov842BlyJluJ2e4JBSx3Hstdtt4U',
    appId: '1:857794246784:ios:c1c6f460c8c3b991d28e65',
    messagingSenderId: '857794246784',
    projectId: 'sorcevapla-e595f',
    storageBucket: 'sorcevapla-e595f.appspot.com',
    iosClientId: '857794246784-eavn9m2lo8ouhptr263oktt02h0s20iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sorcevapla.RunnerTests',
  );
}
